2# Configuration for the ezyang/codemcp server
# Add project-specific details and commands below

project_prompt = """
This is the ElectricianApp_New project.
Please help with coding tasks related to this project.
"""

[commands]
# Add commands relevant to this project, e.g., for building, testing, linting
format = ["./gradlew", "ktlintFormat"]
test = ["./gradlew", "testDebugUnitTest"]
build = ["./gradlew", "assembleDebug"]

# Added Upstash Context7 server
[[servers]]
name = "github.com/upstash/context7"
path = "C:\\Users\\Chris Boyd\\Documents\\Cline\\MCP\\context7"
command = ["node", "dist/index.js"]
